### ISSUE TITLE
Error via `pip install` command

### ISSUE THREAD

**Issue by koddr** [celery/librabbitmq#111]
Hello.

I've error via `pip install` your library:

```shell
$ pip install librabbitmq

Collecting librabbitmq
  Using cached librabbitmq-1.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sb/pctpc4n106j0gncbjwvg9p7m0000gn/T/pycharm-packaging/librabbitmq/setup.py", line 191
        except Exception, exc:
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sb/pctpc4n106j0gncbjwvg9p7m0000gn/T/pycharm-packaging/librabbitmq/

```

How to solve it? Thanks!

**Comment by djgilcrease** [comment]
which version of python are you running?

**Comment by koddr** [comment]
@djgilcrease Python 3.6.4

**Comment by adampl** [comment]
This is because only version 2 is compatible with Python 3, but it hasn't been added to PyPI yet.

**Comment by vbukhonov** [comment]
#113 I have provided a fix for that issue, please check.

**Comment by adampl** [comment]
@thedrow When will you make v2 available in PyPI?

**Comment by thedrow** [comment]
When I'll have free time which is not found in abundance for me these days.
