### ISSUE TITLE
undefined symbol: basic_properties_to_PyDict

### ISSUE THREAD

**Issue by marco-c** [celery/librabbitmq#136]
```
Python 3.7.5 (default, Oct 27 2019, 15:43:29) 
[GCC 9.2.1 20191022] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from librabbitmq import Connection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/.local/lib/python3.7/site-packages/librabbitmq/__init__.py", line 7, in <module>
    import _librabbitmq
ImportError: /home/marco/.local/lib/python3.7/site-packages/_librabbitmq.cpython-37m-x86_64-linux-gnu.so: undefined symbol: basic_properties_to_PyDict
```

This sounds similar to #5.

**Comment by adbharti** [comment]
what is the fix for above?

**Comment by thedrow** [comment]
> 
> 
> what is the fix for above?

#150.
