### ISSUE TITLE
manylinux1 fails

### ISSUE THREAD

**Issue by henryykt** [celery/librabbitmq#146]
Running `sh manylinux1` in the master branch fails:

	+ for PYBIN in '/opt/python/*/bin'
	+ /opt/python/cp27-cp27m/bin/pip wheel /workspace/ -w wheelhouse/
	DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
	Processing /workspace
		ERROR: Complete output from command python setup.py egg_info:
		ERROR: Traceback (most recent call last):
		  File "<string>", line 1, in <module>
		  File "/tmp/pip-req-build-Bgs1KT/setup.py", line 167, in <module>
			if six.PY2:
		NameError: name 'six' is not defined
		----------------------------------------
	ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-Bgs1KT/
	WARNING: You are using pip version 19.1.1, however version 20.0.2 is available.
	You should consider upgrading via the 'pip install --upgrade pip' command.

After updated `if six.PY2:` to `if sys.version_info[0] < 3:` it still fails:

	  /tmp/pip-req-build-rCf1ax/rabbitmq-c/librabbitmq/amqp_socket.c: In function ‘amqp_poll’:
	  /tmp/pip-req-build-rCf1ax/rabbitmq-c/librabbitmq/amqp_socket.c:355:3: error: #error "poll() or select() is needed to compile rabbitmq-c"
	   # error "poll() or select() is needed to compile rabbitmq-c"
		 ^
	  /tmp/pip-req-build-rCf1ax/rabbitmq-c/librabbitmq/amqp_socket.c: In function ‘amqp_login_inner’:
	  /tmp/pip-req-build-rCf1ax/rabbitmq-c/librabbitmq/amqp_socket.c:1334:53: error: ‘AMQ_PLATFORM’ undeclared (first use in this function)
			   amqp_table_construct_utf8_entry("platform", AMQ_PLATFORM);
														   ^
	  /tmp/pip-req-build-rCf1ax/rabbitmq-c/librabbitmq/amqp_socket.c:1334:53: note: each undeclared identifier is reported only once for each function it appears in
	  /tmp/pip-req-build-rCf1ax/rabbitmq-c/librabbitmq/amqp_socket.c: In function ‘amqp_poll’:
	  /tmp/pip-req-build-rCf1ax/rabbitmq-c/librabbitmq/amqp_socket.c:357:1: warning: control reaches end of non-void function [-Wreturn-type]
	   }
	   ^
	  error: command 'gcc' failed with exit status 1
	  ----------------------------------------
	  ERROR: Failed building wheel for librabbitmq
	  Running setup.py clean for librabbitmq
	Failed to build librabbitmq
	ERROR: Failed to build one or more wheels

**Comment by henryykt** [comment]
#147
