### ISSUE TITLE
"Bad frame read" when message with empty body received

### ISSUE THREAD

**Issue by zstyblik** [celery/librabbitmq#54]
I've tested this with the latest version of https://github.com/celery/librabbitmq from pip and https://github.com/alanxz/rabbitmq-c and it seems to be current.

How to replicate:
- create consumer and bind to any type of exchange(I've noticed it with headers, but it happends with any type of exchange)
- send one or more message with an empty body
- traceback should appear

This does happen only when message body is "". Even single white space prevents it from happening.

``` Traceback
2014-08-07 11:40:42,742 ERROR      Thread-1    Traceback (most recent call last):
  File "/scratch/icflix-monitoring-robots/lib/amqp_consumer.py", line 120, in run
    self._connection.drain_events(0.01)
  File "/usr/lib/python2.7/dist-packages/librabbitmq/__init__.py", line 198, in drain_events
    self._basic_recv(timeout)
ChannelError: Bad frame read
```

RabbitMQ log

```
=WARNING REPORT==== 7-Aug-2014::11:28:44 ===
closing AMQP connection <0.5547.0> (192.168.253.9:56556 -> 192.168.253.11:5672):
connection_closed_abruptly
```

**Comment by rodrigohdez1** [comment]
Hello guys,

I'm having this issue (although different exception) using librabbitmq 1.6.1
```
Process processor1_feeder2:
Traceback (most recent call last):
  File "/usr/bin/python-2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/bin/python-2.7.9/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/my-consumer-app/consumer.py", line 107, in run_processes
    connection.drain_events()
  File "/opt/my-consumer-app/env/lib/python2.7/site-packages/librabbitmq/__init__.py", line 220, in drain_events
    self._basic_recv(timeout)
ConnectionError: Bad frame read
```
It seems like #59 was missed in 1.6.1 release as mentioned in #48. :slightly_frowning_face: 
I'm having trouble to keep my consumers alive in production systems as I don't have much control on what other applications / script might be sending. For example, empty messages.
 
Thanks,

**Comment by auvipy** [comment]
try this https://github.com/celery/librabbitmq/releases/tag/v2.0.0 or py-amqp
