### ISSUE TITLE
_librabbitmq.ConnectionError: Couldn't create channel: server connection error 505, message: UNEXPECTED_FRAME - expected content body, got non content body frame instead

### ISSUE THREAD

**Issue by mverrilli** [celery/librabbitmq#72]
I compiled 1.6.1 on Solaris using a gcc 4.8.3 toolchain.  I'm running RabbitMQ 3.5.4 on Erlang 18.0. I get the error above even trying to execute the simple `disabled_basic_get_leak.py` test.  I first discovered the problem when trying to run Celery 3.1.18 for the first time since compiling it and had a hanging beat process.  It works fine with `py-ampq`. Below is the traceback on the test and the compilation below.  

```python
bash-3.2$ python disabled_basic_get_leak.py
Traceback (most recent call last):
  File "disabled_basic_get_leak.py", line 14, in <module>
    c.basic_publish('foo', exchange='getmem', routing_key='getmem')
  File "/opt/app/myapp/software-ng/python/lib/python2.7/site-packages/librabbitmq-1.6.1-py2.7-solaris-2.10-sun4v.64bit.egg/librabbitmq/__init__.py", line 117, in basic_publish
    mandatory or False, immediate or False,
_librabbitmq.ConnectionError: Couldn't create channel: server connection error 505, message: UNEXPECTED_FRAME - expected content body, got non content body frame instead
```

```make
running build
- generating 'clib/librabbitmq/amqp_framing.h'
/opt/app/myapp/software-ng/python/bin/python clib/librabbitmq/codegen.py header rabbitmq-codegen/amqp-rabbitmq-0.9.1.json clib/librabbitmq/amqp_framing.h
- generating 'clib/librabbitmq/amqp_framing.c'
/opt/app/myapp/software-ng/python/bin/python clib/librabbitmq/codegen.py body rabbitmq-codegen/amqp-rabbitmq-0.9.1.json clib/librabbitmq/amqp_framing.c
running build_py
running build_ext
building '_librabbitmq' extension
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c Modules/_librabbitmq/connection.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/Modules/_librabbitmq/connection.o
Modules/_librabbitmq/connection.c: In function ‘PyIter_ToAMQArray’:
Modules/_librabbitmq/connection.c:335:5: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
     while (item = PyIter_Next(iterator)) {
     ^
Modules/_librabbitmq/connection.c:380:1: warning: label ‘error’ defined but not used [-Wunused-label]
 error:
 ^
Modules/_librabbitmq/connection.c: In function ‘PyRabbitMQ_Connection_close’:
Modules/_librabbitmq/connection.c:1043:22: warning: variable ‘reply’ set but not used [-Wunused-but-set-variable]
     amqp_rpc_reply_t reply;
                      ^
Modules/_librabbitmq/connection.c: In function ‘PyRabbitMQ_Connection_basic_cancel’:
Modules/_librabbitmq/connection.c:1863:29: warning: variable ‘ok’ set but not used [-Wunused-but-set-variable]
     amqp_basic_cancel_ok_t *ok;
                             ^
Modules/_librabbitmq/connection.c: In function ‘PyRabbitMQ_Connection_flow’:
Modules/_librabbitmq/connection.c:1988:29: warning: variable ‘ok’ set but not used [-Wunused-but-set-variable]
     amqp_channel_flow_ok_t *ok;
                             ^
Modules/_librabbitmq/connection.c: In function ‘PyRabbitMQ_Connection_basic_recover’:
Modules/_librabbitmq/connection.c:2021:30: warning: variable ‘ok’ set but not used [-Wunused-but-set-variable]
     amqp_basic_recover_ok_t *ok;
                              ^
Modules/_librabbitmq/connection.c: At top level:
Modules/_librabbitmq/connection.c:719:26: warning: ‘PyDict_ToAMQTable’ is static but used in inline function ‘PyDict_to_basic_properties’ which is not static [enabled by default]
         props->headers = PyDict_ToAMQTable(conn, value, pool);
                          ^
Modules/_librabbitmq/connection.c:496:17: warning: ‘AMQTable_toPyDict’ is static but used in inline function ‘basic_properties_to_PyDict’ which is not static [enabled by default]
         value = AMQTable_toPyDict(&(props->headers));
                 ^
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c clib/librabbitmq/amqp_api.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_api.o
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c clib/librabbitmq/amqp_connection.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_connection.o
clib/librabbitmq/amqp_connection.c: In function ‘amqp_send_frame’:
clib/librabbitmq/amqp_connection.c:466:21: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
     iov[2].iov_base = &frame_end_byte;
                     ^
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c clib/librabbitmq/amqp_consumer.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_consumer.o
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c clib/librabbitmq/amqp_framing.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_framing.o
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c clib/librabbitmq/amqp_hostcheck.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_hostcheck.o
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c clib/librabbitmq/amqp_mem.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_mem.o
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c clib/librabbitmq/amqp_socket.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_socket.o
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c clib/librabbitmq/amqp_table.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_table.o
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c clib/librabbitmq/amqp_tcp_socket.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_tcp_socket.o
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c clib/librabbitmq/amqp_timer.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_timer.o
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include -fPIC -Iclib/librabbitmq -Iclib -I/opt/app/myapp/software-ng/python/include/python2.7 -c clib/librabbitmq/amqp_url.c -o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_url.o
gcc -shared -L/opt/app/myapp/software-ng/common/lib -L/opt/app/myapp/software-ng/common/lib/sparcv9 -R/opt/app/myapp/software-ng/common/lib -R/opt/app/myapp/software-ng/common/lib/sparcv9 -L/opt/app/myapp/software-ng/common/lib -L/opt/app/myapp/software-ng/common/lib/sparcv9 -R/opt/app/myapp/software-ng/common/lib -R/opt/app/myapp/software-ng/common/lib/sparcv9 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wstrict-prototypes -DHAVE_CONFIG_H -I/opt/app/myapp/software-ng/common/include build/temp.solaris-2.10-sun4v.64bit-2.7/Modules/_librabbitmq/connection.o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_api.o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_connection.o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_consumer.o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_framing.o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_hostcheck.o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_mem.o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_socket.o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_table.o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_tcp_socket.o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_timer.o build/temp.solaris-2.10-sun4v.64bit-2.7/clib/librabbitmq/amqp_url.o -o build/lib.solaris-2.10-sun4v.64bit-2.7/_librabbitmq.so
running install
```

**Comment by mverrilli** [comment]
Quite a few tests fail when running the test script.  The interesting thing is that when I use a 32-bit toolchain, my tests actually do work even though the setup tests fail in the exact same was as this one.

```
$ python ./setup.py test
running test
running egg_info
writing requirements to librabbitmq.egg-info/requires.txt
writing librabbitmq.egg-info/PKG-INFO
writing top-level names to librabbitmq.egg-info/top_level.txt
writing dependency_links to librabbitmq.egg-info/dependency_links.txt
reading manifest file 'librabbitmq.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'tests'
no previously-included directories found matching '*.pyc'
no previously-included directories found matching '*.o'
no previously-included directories found matching '*.la'
no previously-included directories found matching '*.so'
no previously-included directories found matching '*.dylib'
writing manifest file 'librabbitmq.egg-info/SOURCES.txt'
running build_ext
copying build/lib.solaris-2.10-sun4v.64bit-2.7/_librabbitmq.so ->
test_basic_get_ack (librabbitmq.tests.test_functional.test_Channel) ... ERROR
test_send_message (librabbitmq.tests.test_functional.test_Channel) ... ok
test_timeout (librabbitmq.tests.test_functional.test_Channel)
Check that our ``drain_events`` call actually times out if ... ERROR
test_timeout_burst (librabbitmq.tests.test_functional.test_Channel)
Check that if we have a large burst of messages in our queue ... ERROR
test_delete (librabbitmq.tests.test_functional.test_Delete)
Test that we can declare a channel delete it, and then declare with ... ok
test_delete_empty (librabbitmq.tests.test_functional.test_Delete)
Test that the queue doesn't get deleted if it is not empty ... ERROR

======================================================================
ERROR: test_basic_get_ack (librabbitmq.tests.test_functional.test_Channel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tng/librabbitmq-1.6.1/librabbitmq/tests/test_functional.py", line 50, in test_basic_get_ack
    x = self.channel.basic_get(TEST_QUEUE)
  File "/tmp/tng/librabbitmq-1.6.1/librabbitmq/__init__.py", line 67, in basic_get
    frame = self.connection._basic_get(self.channel_id, queue, no_ack)
ConnectionError: Bad frame read

======================================================================
ERROR: test_timeout (librabbitmq.tests.test_functional.test_Channel)
Check that our ``drain_events`` call actually times out if
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tng/librabbitmq-1.6.1/librabbitmq/tests/test_functional.py", line 103, in test_timeout
    self.connection.drain_events(timeout=0.1)
  File "/tmp/tng/librabbitmq-1.6.1/librabbitmq/__init__.py", line 220, in drain_events
    self._basic_recv(timeout)
ConnectionError: Bad frame read

======================================================================
ERROR: test_timeout_burst (librabbitmq.tests.test_functional.test_Channel)
Check that if we have a large burst of messages in our queue
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tng/librabbitmq-1.6.1/librabbitmq/tests/test_functional.py", line 83, in test_timeout_burst
    self.connection.drain_events(timeout=0.2)
  File "/tmp/tng/librabbitmq-1.6.1/librabbitmq/__init__.py", line 220, in drain_events
    self._basic_recv(timeout)
ConnectionError: Bad frame read

======================================================================
ERROR: test_delete_empty (librabbitmq.tests.test_functional.test_Delete)
Test that the queue doesn't get deleted if it is not empty
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tng/librabbitmq-1.6.1/librabbitmq/tests/test_functional.py", line 167, in test_delete_empty
    x = self.channel.basic_get(self.TEST_QUEUE)
  File "/tmp/tng/librabbitmq-1.6.1/librabbitmq/__init__.py", line 67, in basic_get
    frame = self.connection._basic_get(self.channel_id, queue, no_ack)
ConnectionError: Bad frame read

----------------------------------------------------------------------
Ran 6 tests in 0.525s

FAILED (errors=4)
```

**Comment by mverrilli** [comment]
Also, I have run many of the examples in the clib examples folder all with success.  (producer/consumer, listen/send, etc).

**Comment by mverrilli** [comment]
I've traced down the packets to: 
Working (32-bit compile): `02:00:01:00:00:00:12:00:3c:00:00:00:00:00:00:00:00:00:03:20:00:00:00:00:00:ce`
Not working (64-bit compile): `02:00:01:00:00:00:12:00:3c:00:00:00:00:00:03:00:00:00:00:20:00:00:00:00:00:ce`

Breaking it down, you see the body size field of the content header packet looks like an endian issue: 
`00:00:00:00:00:00:00:03` vs `00:00:00:03:00:00:00:00`

**Comment by mverrilli** [comment]
Figured it out I think.  body_size was defined as a pointer and so changes depending on your environment. Should be a int32_t.  I submitted a pull request.  Let me know if I got it wrong.

**Comment by mverrilli** [comment]
Ok I see the real issue now. Two things.  

#1. PY_SSIZE_T_CLEAN needs to be defined before including Python.h.  
#2. PY_SIZE_TYPE should be used for body_size. 

I'll scan for more areas like this if I can find them.

**Comment by mverrilli** [comment]
Please see pull request #74 to address this issue.

**Comment by mverrilli** [comment]
Pull request was committed. Closing issue.
