### ISSUE TITLE
Support the 'Auth Failure' RabbitMQ protocol extension

### ISSUE THREAD

**Issue by edmorley** [celery/librabbitmq#89]
Support was added to rabbitmq-c in alanxz/rabbitmq-c#196, however librabbitmq still treats auth failures as generic socket errors, rather than providing a more specific exception.

eg with librabbitmq 1.6.1, kombu 3.0.35, Python 2.7.12 on Ubuntu 16.04 and using the STR from celery/kombu#611:

```
Traceback (most recent call last):
  File "./kombu-test.py", line 6, in <module>
    connection.connect()
  File "/home/vagrant/.virtualenvs/kombu2/local/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/home/vagrant/.virtualenvs/kombu2/local/lib/python2.7/site-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
  File "/home/vagrant/.virtualenvs/kombu2/local/lib/python2.7/site-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/vagrant/.virtualenvs/kombu2/local/lib/python2.7/site-packages/kombu/transport/librabbitmq.py", line 123, in establish_connection
    conn = self.Connection(**opts)
  File "/home/vagrant/.virtualenvs/kombu2/local/lib/python2.7/site-packages/librabbitmq/__init__.py", line 199, in __init__
    self.connect()
_librabbitmq.ConnectionError: Couldn't log in: a socket error occurred
```

See:
http://www.rabbitmq.com/auth-notification.html

**Comment by edmorley** [comment]
Ah so the situation was slightly improved in #49, however:
* a new librabbitmq release hasn't been made since then
* it still requires opting in (I think the capability should be set by default)
* even with the capability set, the exception is something like `_librabbitmq.ConnectionError: Couldn't log in: unexpected method received` (I can't test for sure, due to #90), so needs additional support

**Comment by auvipy** [comment]
thanks for report and sorry for late response. I will be back to you soon.
